--audio-format mp3
--audio-quality 0
--add-metadata
--split-chapters
--embed-thumbnail
--ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
--output "chapter:%(title)s/%(section_number)02d %(section_title)s.%(ext)s"
